version: '3.9'

services:
    app:
        container_name: css-html-practice
        image: css-html-practice
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '3001:80'
