# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - csspracticewebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerstests.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d4740031e5994416830d0ca747f2dd7a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ca8c1d518c0948fbb085ddb3710d631b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerstests.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d4740031e5994416830d0ca747f2dd7a }}/css-practice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'csspracticewebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ee0e1c3c192c44fa8165ef65d1e5add0 }}
        images: 'containerstests.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d4740031e5994416830d0ca747f2dd7a }}/css-practice:${{ github.sha }}'